version: "3.9"
services:
  client:
    build: ./client
    ports:
      - "3000:3000"
    volumes:
      - "./client:/app"
  api:
    build: ./api
    ports:
      - "8080:8080"
    volumes:
      - "./api:/app"
