version: "3.9"
services:
  client:
    build:
      context: ./client
      dockerfile: ./Dockerfile.production
    ports:
      - "3000:3000"
    volumes:
      - "./client:/app"
      - build-image:/app/.next
  api:
    build: ./api
    env_file: ./api/.env
    ports:
      - "8080:8080"
    volumes:
      - "./api:/app"
    networks:
      - cycle-net
    environment:
      GIN_MODE: release
    depends_on:
      - mysql
  mysql:
    platform: linux/x86_64
    image: mysql:8.0
    volumes:
      - mysql_data:/var/lib/mysql
    env_file:
      - ./mysql.env
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    container_name: mysql-container
    networks:
      - cycle-net
    ports:
      - "3306:3306"

volumes:
  mysql_data:
  build-image:

networks:
  cycle-net:
    driver: bridge
